### ISSUE TITLE
Is this supposted to be empty?

### ISSUE THREAD

**Issue by mollthecoder** [MiniCoder11/BlueOS-Node-Backend-Rewrite#1]
I kinda wanna see the source of the backend so I can make my own.

You've seen me on scratch.

**Comment by MiniCoder11** [comment]
> I kinda wanna see the source of the backend so I can make my own.
> 
> You've seen me on scratch.

This repository somehow never got used. Try this one: https://github.com/MiniCoder11/BlueOS-Node-Backend.

**Comment by mollthecoder** [comment]
Thanks.
